### PR TITLE
Fixing README for Agentless scanning

### PR DESCRIPTION
**Pull request by ravinadhruve10**
- renaming variables from 'agentless' to 'scanning' in README
- updated the input and output variables

### CODE REVIEW

**Review by haresh-suresh — DISMISSED** [review]

**Comment by cgeers** [comment]
> removing default value for scanning_account_id and making it a required variable, since now the value will be coming from the BE

I accept the premise, but I remain uncertain this is actually a wise thing to do.  The degree to which these modules able to be invoked directly (without BE support) is a common ask, and the use cases are valid, IMO. However, we have never formally designed for this, and as such, support is hit or miss. This choice adds another miss.

Not advocated for hard coded constants of course, just trying to think of the big picture.

**Review by cgeers — DISMISSED** [review]

**Comment by ravinadhruve10** [comment]
> > removing default value for scanning_account_id and making it a required variable, since now the value will be coming from the BE
> 
> I accept the premise, but I remain uncertain this is actually a wise thing to do. The degree to which these modules able to be invoked directly (without BE support) is a common ask, and the use cases are valid, IMO. However, we have never formally designed for this, and as such, support is hit or miss. This choice adds another miss.
> 
> Not advocating for hard coded constants of course, just trying to think of the big picture.

I see your point which we need to think about. However, my concern here is since this is a public repo shall we be mentioning our prod accountId, from security perspective?

**Comment by cgeers** [comment]
> I see your point which we need to think about. However, my concern here is since this is a public repo shall we be mentioning our prod accountId, from security perspective?

If this is a secret, then it should be treated that way -- scrubbed from the history of this repo, and changed. Ultimately it is not a secret of course. Disclosure of an account number is not _actually_ a security issue, it just looks funny -- and it does. But, not delineating this distinction also says something -- not great.

This circumstance is actually more akin to using DNS names versus IPs. If such a thing as a globally unique account alias, publicly resolvable to the account ID, and controlled by the account owner, I doubt anyone would bat an eye, yet it'd be effectively the same exact thing. Normal AWS account aliases come close to this, but aren't readily "resolvable" by some standard mechanism.

**Comment by ravinadhruve10** [comment]
> > I see your point which we need to think about. However, my concern here is since this is a public repo shall we be mentioning our prod accountId, from security perspective?
> 
> If this is a secret, then it should be treated that way -- scrubbed from the history of this repo, and changed. Ultimately it is not a secret of course. Disclosure of an account number is not _actually_ a security issue, it just looks funny -- and it does. But, this distinction is important.
> 
> This circumstance is actually more akin to using DNS names versus IPs. If such a thing as a globally unique account alias, publicly resolvable to the account ID, and controlled by the account owner, I doubt anyone would bat an eye, yet it'd be effectively the same exact thing. Normal AWS account aliases come close to this, but aren't readily "resolvable" by some standard mechanism.

Hmm, let me add back the default for now, and we can circle back on this.

That's a good analogy, and I agree it will effectively be the same thing - using accountId or an account alias. FWIW one point here is, we would like to preferably keep the approach same whether its AWS, GCP or Azure in the future if and when we support scanning for other cloud environments. (maybe too much of future thinking here)

**Review by cgeers — APPROVED** [review]

**Pull request merged**
